// Modern 2026 design system - clean, vibrant, accessible
const palette = {
  // Light mode
  light: {
    ink: "#1C1C1E",
    inkSecondary: "#3C3C43",
    muted: "#8E8E93",
    background: "#F2F2F7",
    backgroundElevated: "#FFFFFF",
    surface: "#FFFFFF",
    surfaceSecondary: "rgba(118, 118, 128, 0.12)",
    card: "#FFFFFF",
    separator: "rgba(60, 60, 67, 0.12)",
  },
  // Dark mode
  dark: {
    ink: "#FFFFFF",
    inkSecondary: "#EBEBF5",
    muted: "#98989D",
    background: "#000000",
    backgroundElevated: "#1C1C1E",
    surface: "#1C1C1E",
    surfaceSecondary: "rgba(118, 118, 128, 0.24)",
    card: "#2C2C2E",
    separator: "rgba(84, 84, 88, 0.65)",
  },
  // Shared accent colors
  accent: {
    blue: "#007AFF",
    green: "#34C759",
    orange: "#FF9500",
    pink: "#FF2D55",
    purple: "#AF52DE",
    teal: "#5AC8FA",
    indigo: "#5856D6",
    mint: "#00C7BE",
    coral: "#FF6B6B",
  },
  // Gradient pairs
  gradients: {
    sunrise: ["#FF9500", "#FF2D55"],
    ocean: ["#007AFF", "#5AC8FA"],
    forest: ["#34C759", "#32ADE6"],
    sunset: ["#FF2D55", "#AF52DE"],
    night: ["#5856D6", "#AF52DE"],
    mint: ["#00C7BE", "#34C759"],
  },
} as const;

export default {
  light: {
    text: palette.light.ink,
    textSecondary: palette.light.inkSecondary,
    background: palette.light.background,
    backgroundElevated: palette.light.backgroundElevated,
    surface: palette.light.surface,
    surfaceSecondary: palette.light.surfaceSecondary,
    card: palette.light.card,
    border: palette.light.separator,
    tint: palette.accent.blue,
    accent: palette.accent.purple,
    accentSecondary: palette.accent.teal,
    mutedText: palette.light.muted,
    success: palette.accent.green,
    warning: palette.accent.orange,
    error: palette.accent.pink,
    shadow: "rgba(0, 0, 0, 0.08)",
    shadowLight: "rgba(0, 0, 0, 0.04)",
    shadowStrong: "rgba(0, 0, 0, 0.12)",
    gradients: palette.gradients,
    accents: palette.accent,
  },
  dark: {
    text: palette.dark.ink,
    textSecondary: palette.dark.inkSecondary,
    background: palette.dark.background,
    backgroundElevated: palette.dark.backgroundElevated,
    surface: palette.dark.surface,
    surfaceSecondary: palette.dark.surfaceSecondary,
    card: palette.dark.card,
    border: palette.dark.separator,
    tint: palette.accent.blue,
    accent: palette.accent.purple,
    accentSecondary: palette.accent.teal,
    mutedText: palette.dark.muted,
    success: palette.accent.green,
    warning: palette.accent.orange,
    error: palette.accent.pink,
    shadow: "rgba(0, 0, 0, 0.3)",
    shadowLight: "rgba(0, 0, 0, 0.2)",
    shadowStrong: "rgba(0, 0, 0, 0.5)",
    gradients: palette.gradients,
    accents: palette.accent,
  },
};
