import { z } from "zod";


const GEMINI_API_KEY = process.env.EXPO_PUBLIC_GEMINI_API_KEY;

// Google Places API (New) - Text Search
// Docs: https://developers.google.com/maps/documentation/places/web-service/text-search

async function searchGooglePlaces(
  query: string
): Promise<LocationLookupResult | null> {
  if (!GEMINI_API_KEY) return null;

  try {
    console.log(`[GooglePlaces] Searching text: "${query}"`);

    // We request specific fields to manage costs (places.id, places.displayName, places.formattedAddress, places.location)
    const response = await fetch(
      `https://places.googleapis.com/v1/places:searchText`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "X-Goog-Api-Key": GEMINI_API_KEY,
          "X-Goog-FieldMask": "places.displayName,places.formattedAddress,places.location,places.id",
        },
        body: JSON.stringify({
          textQuery: query,
          maxResultCount: 1, // We only need the top match
        }),
      }
    );

    if (!response.ok) {
      const errorText = await response.text();
      console.error("[GooglePlaces] API Error. Status:", response.status);
      console.error("[GooglePlaces] Error Body:", errorText);
      console.error("[GooglePlaces] TIP: Ensure 'Places API (New)' is enabled in Google Cloud Console AND Billing is enabled.");
      return null;
    }

    const data = await response.json();
    const place = data.places?.[0];

    if (!place) {
      console.warn("[GooglePlaces] No results found.");
      return null;
    }

    console.log("[GooglePlaces] Found:", place.displayName?.text);

    return {
      latitude: place.location?.latitude ?? null,
      longitude: place.location?.longitude ?? null,
      formattedAddress: place.formattedAddress ?? null,
      mapsUrl: null, // Will be generated by caller
    };

  } catch (error) {
    console.error("[GooglePlaces] Network error", error);
    return null;
  }
}

export type LocationLookupResult = {
  latitude: number | null;
  longitude: number | null;
  formattedAddress: string | null;
  mapsUrl: string | null;
};

const LocationSchema = z.object({
  latitude: z
    .number()
    .describe("Latitude coordinate of the location")
    .nullable(),
  longitude: z
    .number()
    .describe("Longitude coordinate of the location")
    .nullable(),
  formattedAddress: z
    .string()
    .describe("Full formatted address of the location")
    .nullable(),
  city: z
    .string()
    .describe("City name if identifiable")
    .nullable(),
  country: z
    .string()
    .describe("Country name if identifiable")
    .nullable(),
});

export async function lookupLocationCoordinates(params: {
  locationName: string;
  title?: string;
  context?: string;
  streetAddress?: string | null;
  neighborhood?: string | null;
  city?: string | null;
  state?: string | null;
  country?: string | null;
}): Promise<LocationLookupResult> {
  const { locationName, streetAddress, neighborhood, city, state, country } = params;

  // 1. Construct a search query for Google Maps
  // Priority: "Publique Bakery, Melbourne, Australia"
  // Bias: Always append the broader context if not present.

  const queryParts = [locationName];

  if (streetAddress) queryParts.push(streetAddress);
  if (neighborhood) queryParts.push(neighborhood);
  if (city) queryParts.push(city);

  // If no city/country in extracted data, inject Australian context
  // This satisfies the user's request to "focus on Australia"
  const hasOzContext = [locationName, city, country, state].some(s =>
    s && (s.toLowerCase().includes('melbourne') || s.toLowerCase().includes('australia') || s.toLowerCase().includes('victoria') || s.toLowerCase() === 'vic')
  );

  if (!hasOzContext) {
    queryParts.push("Melbourne, Australia");
  } else {
    // Just ensure state/country are there if we have them
    if (state) queryParts.push(state);
    if (country) queryParts.push(country);
  }

  const searchQuery = queryParts.join(", ");

  console.log("[lookupLocationCoordinates] Search Query:", searchQuery);

  if (!GEMINI_API_KEY) {
    console.error("[lookupLocationCoordinates] No API key");
    return { latitude: null, longitude: null, formattedAddress: null, mapsUrl: null };
  }

  // 2. Call Google Places API
  const placeResult = await searchGooglePlaces(searchQuery);

  if (placeResult && placeResult.latitude && placeResult.longitude) {
    // Generate the open URI used for the "Directions" button
    const queryEncoded = encodeURIComponent(placeResult.formattedAddress || locationName);
    const mapsUrl = `https://www.google.com/maps/search/?api=1&query=${queryEncoded}&query_place_id=${placeResult.latitude},${placeResult.longitude}`;

    return {
      ...placeResult,
      mapsUrl
    };
  }

  // 3. Fallback: Return NULL as requested. No "best guesses".
  console.warn("[lookupLocationCoordinates] Places API failed to return coords. Returning null.");
  return {
    latitude: null,
    longitude: null,
    formattedAddress: null,
    mapsUrl: null,
  };

  return {
    latitude: null,
    longitude: null,
    formattedAddress: null,
    mapsUrl: null,
  };
}

export function generateGoogleMapsUrl(params: {
  latitude?: number | null;
  longitude?: number | null;
  query?: string | null;
}): string | null {
  const { latitude, longitude, query } = params;

  if (latitude != null && longitude != null) {
    const q = query ? encodeURIComponent(query) : `${latitude},${longitude}`;
    return `https://www.google.com/maps/search/?api=1&query=${q}`;
  }

  if (query) {
    return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`;
  }

  return null;
}
